{{- if and (.Values.hiera.eyaml.private_key) (not .Values.r10k.hiera.viaSsh.credentials.existingSecret) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: eyamlpriv-config
  labels:
    {{- include "puppetserver.hiera.labels" . | nindent 4 }}
data:
  private_key.pkcs7.pem: |-
    {{ .Values.hiera.eyaml.private_key | nindent 4 }}
{{- end }}
