---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: control-repo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/lilship/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: control-repo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
