{{- if .Values.puppetserver.preGeneratedCertsJob.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "puppetserver.name" . }}-puppetdb-preinstall
  labels:
    {{- include "puppetserver.puppetdb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
binaryData:
  {{- $root := . }}
  {{- range $path, $bytes := .Files.Glob "init/puppet-certs/puppetdb/*.gz" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc | quote }}
  {{- end }}
{{- end }}
