apiVersion: v1
kind: Service
metadata:
  name: {{ include "pupagent.fullname" . }}
  labels:
    {{- include "pupagent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pupagent.selectorLabels" . | nindent 4 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pupagent.fullname" . }}
  labels:
    {{- include "pupagent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http8080
      protocol: TCP
      name: http8080
  selector:
    {{- include "pupagent.selectorLabels" . | nindent 4 }}
