ARG ubuntu_version=20.04

FROM ubuntu:${ubuntu_version}

ARG version="7.0.0"
ARG vcs_ref
ARG build_date
ARG UBUNTU_CODENAME="focal"

ENV PATH=/opt/puppetlabs/server/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin:$PATH

ENTRYPOINT ["/opt/puppetlabs/bin/puppet"]
CMD ["agent", "--verbose", "--onetime", "--no-daemonize", "--summarize"]
expose 80 8080

ADD https://apt.puppetlabs.com/puppet7-release-"$UBUNTU_CODENAME".deb /puppet7.deb

# hadolint ignore=DL3008
RUN dpkg -i /puppet7.deb && \
    rm /puppet7.deb && \
    apt-get update && \
    apt-get install --no-install-recommends -y ca-certificates lsb-release puppet-agent="$version"-1"$UBUNTU_CODENAME" && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

