FROM golang:alpine3.13 as builder
RUN apk add --update git && \
  mkdir -p /tmp/gotty && \
  GO111MODULE=off GOPATH=/tmp/gotty go get github.com/yudai/gotty

FROM alpine:3.12.4
COPY --from=builder /tmp/gotty/bin/gotty /usr/bin/gotty
RUN apk add --update bash tmux
ENV TERM=xterm
EXPOSE 8080

CMD ["/usr/bin/gotty","--permit-write","--permit-arguments","--reconnect","tmux"]
