apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lilgitserver.fullname" . }}
  labels:
    {{- include "lilgitserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lilgitserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lilgitserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lilgitserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: gitlilship
          secret:
            secretName: gitssh
            defaultMode: 0600
            items:
            - key: id_rsa
              path: id_rsa
            - key: authorized_keys
              path: authorized_keys
            - key: known_hosts
              path: known_hosts
        - name: gitlilship
          persistentVolumeClaim:
            claimName: gitlilship
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - mountPath: "/tmp/lilship"
              name: gitlilship
            - mountPath: "/home/git/.ssh"
              name: lilgit
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
