{{- if not .Values.global.credentials.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "puppetdb.secret" . }}
  labels:
    {{- include "puppetserver.puppetdb.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.global.credentials.username | b64enc | quote }}
  password: {{ include "postgresql.password" . | b64enc | quote }}
{{- end -}}
